name = "GenTF"
uuid = "1956f2fc-1631-11e9-1597-3d3589996c0f"
authors = ["Marco Cusumano-Towner <imarcoam@gmail.com>"]
version = "0.1.0"

[deps]
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]   	
test = ["Test"]
